development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cloudstreet/api_development

dev:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cloudstreet/api_development

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cloudstreet/api_staging

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cloudstreet/api_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cloudstreet/api_production