openshift_report_feature:
  openshift_utilization_report_api
emr_cluster_aws_csv_feature:
  emr_cluster_aws_csv_download
fetch_subscription_tags_with_combined_approach_feature:
  fetch_subscription_tags_with_combined_approach
aws_move_edp_cost_from_na_to_respective_services_feature:
  aws_move_edp_cost_from_na_to_respective_services
aws_support_for_cardinality_based_query_feature:
  aws_support_for_cardinality_based_query
aws_billing_multiple_report_config_feature:
  aws_billing_multiple_report_config_from_different_account
sankey_chart_services_feature:
  cost_allocation_reports
aws_manual_export_report_configuration_feature:
  aws_manual_export_report_configuration
awsbc_percentage_of_spend_based_on_service_or_item_description_feature:
  awsbc_percentage_of_spend_based_on_service_or_item_description
awsbc_usage_quantity_multiplier_feature:
  awsbc_usage_quantity_multiplier
awsbc_percentage_of_spend_based_on_billing_entity_feature:
  awsbc_percentage_of_spend_based_on_billing_entity
azuress_support_addtional_azure_tenants_for_normal_adapter_feature:
  azuress_support_addtional_azure_tenants_for_normal_adapter
awsbc_specific_day_of_month_fixed_margin_discount_feature:
  awsbc_specific_day_of_month_fixed_margin_discount
awsbc_based_on_daily_daterange_feature:
  awsbc_based_on_daily_daterange
awsbc_enable_reoccurring_for_all_subsequent_months_feature:
  awsbc_enable_reoccurring_for_all_subsequent_months
awsbc_percentage_of_spend_based_on_usage_type_feature:
  awsbc_percentage_of_spend_based_on_usage_type
awsbc_percentage_of_spend_based_on_operation_feature:
  awsbc_percentage_of_spend_based_on_operation
awsbc_percentage_of_spend_based_on_charge_type_feature:
  awsbc_percentage_of_spend_based_on_charge_type
awsbc_usage_quantity_multiplier_based_on_item_description_feature:
  awsbc_usage_quantity_multiplier_based_on_item_description
awsbc_usage_quantity_multiplier_based_on_usage_type_feature:
  awsbc_usage_quantity_multiplier_based_on_usage_type
awsbc_usage_quantity_multiplier_based_on_charge_type_feature:
  awsbc_usage_quantity_multiplier_based_on_charge_type
awsbc_usage_quantity_multiplier_based_on_operation_feature:
  awsbc_usage_quantity_multiplier_based_on_operation
awsrispbc_within_account_group_based_on_usage_feature:
  awsrispbc_within_account_group_based_on_usage
openshift_services_feature:
  openshift_allocation_reports
aws_azure_po_config_feature:
  aws_azure_po_config
